name: 🟢 Deploy Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          default-branch: main

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: pcov

      - name: Install PHP dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: '-oa --no-dev'

      - name: Install and Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies
        run: |
          npm install
          npm run build

      - name: 🚀 Deploy WordPress Plugin
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SLUG: sim-site-maintenance
            BUILD_DIR: ./build/trunk/
            INPUT_DRY_RUN: true
            VERSION: 0.2.8
